### ISSUE TITLE
HA 104.0 breaks sonoff_lan_mode_r3 works fine in 103.4 and started working again when back to 103.4

### ISSUE THREAD

**Issue by trentjw** [mattsaxon/sonoff-lan-mode-homeassistant#18]

**Comment by mattsaxon** [comment]
I haven’t checked (ie upgrade), but I would guess it down to the dependant zeroconf that 104 comes with. There are some issues with the later versions that I’m working on. Does you setup allow you to install a specific version of a dependancy, if so please ‘pip install ‘zeroconf==0.23.0’ and see if that helps.

**Comment by trentjw** [comment]
I have 16 devices that uses this and with 104 in shows all unavailable except for one or two of them and it picks random ones on each reboot but never picked all up untill I reverted back to 103.4 and it worked like it should. does reverting back to  revert zerocong as well?

my setup is Venv install on raspberry 4 if that makes any difference

**Comment by TheSDTM** [comment]
> I haven’t checked (ie upgrade), but I would guess it down to the dependant zeroconf that 104 comes with. There are some issues with the later versions that I’m working on. Does you setup allow you to install a specific version of a dependancy, if so please ‘pip install ‘zeroconf==0.23.0’ and see if that helps.

I can confirm that installing zeroconf 0.23.0 resolves an issue on HA 104

**Comment by mattsaxon** [comment]
Thanks for the feedback. I’m looking at a variety of issues with zeroconf at the moment.

**Comment by tsouza85** [comment]
Only zeroconf downgrade did not solve, I had to revert version to 103.4

**Comment by trentjw** [comment]
Update on the Issue of 104.1 tried installing full off reboot it finds all 16 devices and they work as should just a server reboot and it can only find one device of the 16, each server reboot yields one random switch of my 16 the rest show as unavailable going back to 103.4 yet again

**Comment by TheSDTM** [comment]
> Update on the Issue of 104.1 tried installing full off reboot it finds all 16 devices and they work as should just a server reboot and it can only find one device of the 16, each server reboot yields one random switch of my 16 the rest show as unavailable going back to 103.4 yet again

It is because HA automatically upgrades zeroconf back to 0.24 after rebooting. On first boot after installing is uses 0.23, but then it upgrades to 0.24

**Comment by Bluhme1** [comment]
Advice needed. How can I downgrade zeroconf in a Hassio docker Installation?

**Comment by mattsaxon** [comment]
Logon to terminal as root and then use ‘docker exec homeassistant pip install ‘zeroconf==0.23.0’

**Comment by Bluhme1** [comment]
Found by accident / luck a new version of your custom_component dated 8 days ago. Installed it by copying it to /config/custom_components/sonoff_lan_mode_r3. Restarted and my entities came back. Maybe a coincidence but I am not restarting again before you announce a solution.:-)
Thank you for your effort. I have been using your component for quite a while without any problems and you have sorted out problems before, so I am confident that you will succeed this time also

**Comment by mattsaxon** [comment]
The newer version is improved, but the root problem is down to a faulty zeroconf. I do have a workaround in the newer code, but I don't think it is completely reliable. I'm working towards a fix in the dependant zeroconf component, meanwhile if you have issues, revert to older zeroconf as described above.

**Comment by mattsaxon** [comment]
@tsouza85, I suspect you didn't backout zeroconf correctly, can you ensure you did this in the container running home assistant? Also you will need to restart HA.

**Comment by mattsaxon** [comment]
I've just tested with 0.104.2, this has the very latest zeroconf==0.24.4 with a fix I made to it.

This works well as far as I can see.

Can others confirm what version of zeroconf they are having issues with as I can tell from the HA logs exactly what version comes with which sub-release of zerconf. In the HA release notes there were upgrades to 0.24.1, 0.24.2, 0.24.3 and 0.24.4!

EDIT: corrected 0.104.3 to 0.104.2

**Comment by Bluhme1** [comment]
Exiting news. I haven't seen 0.104.3 yet

**Comment by tsouza85** [comment]
@mattsaxon 
I tested again in version 104.2 with zeroconf 0.23, the lights work, but ifan02 still has problems. 
I went back to version 103.4 and everything works ...

EDIT: 
Version sonoff_lan_mode_r3 was out of date.
Everything ok with HA 104.2 and zeroconf 24.4 .

Thanks!

**Comment by mattsaxon** [comment]
@Bluhme1, sorry, I think that's just a typo, I should have said 0.104.2. Anyway as @tsouza85 confirms latest code of everything works as expected.
