### ISSUE TITLE
Sonoff Basic R3 DIY mode with 3.3.0 firmware

### ISSUE THREAD

**Issue by Bluhme1** [mattsaxon/sonoff-lan-mode-homeassistant#2]
[error log.txt](https://github.com/mattsaxon/sonoff-lan-mode-homeassistant/files/3437054/error.log.txt)

I finally received a Sonoff Basic R3 and succeeded in getting it into DIY mode and establish a connection to the DIY demo app. A bit complicated.
Tried to put it into Home Assistant using your component. The switch was created but I cannot activate on or off. But when I turn the Sonoff Basic R3 on in the demo program or manually by pressing the switch, the status of the switch in HA changes status. But in HA the switch doesn’t work.
Sonoff firmware version 3.30
switch.yaml:
  - platform: sonoff_lan_mode_r3
    name: test
    device_id: 100086f13b

**Comment by mattsaxon** [comment]
I can't see any information in the log from the device you mention above, There are 4 other devices mentioned however; 10005eb925, 10007d04f8, 100063875f, 100063967e.

Are these working?

If you could somehow format future posted log with CRLF, that would be useful as it was very difficult to parse.

**Comment by Bluhme1** [comment]
Here is a new error.log. If you search 100086f13b (which is the ID of the Sonoff Device) you will find 16 instances

Everything else is working. Is the log formatted in the right way. If not, please explain in a bit more detail how to do it

/Lars

**Comment by mattsaxon** [comment]
Sorry, I can't see the log at all, did you attach it?

Can you confirm you have a set of other devices that are working  please? What models are they and are any the same as the problem device?

**Comment by Bluhme1** [comment]
Sorry. A classical mistake. Here is the log.

[log.txt](https://github.com/mattsaxon/sonoff-lan-mode-homeassistant/files/3464311/log.txt)

I have a number of other devices running on your component. Sonoff Basic R2, S20 and S26. And also one Sonoff Basic R3 in normal (not DIY) mode and with autentification.
So I think it must be a problem with the new firmware 3.3.0 and DIY mode

**Comment by mattsaxon** [comment]
Thanks for the log. Its not formatted as well as it could be, but I can read it anyway. The device is returning a 400 error

> response received: <Response [200]> b'\{"seq":56,"error":400\}'\
2019-08-03 10:16:17 WARNING (SyncWorker_16) [homeassistant.components.switch.sonoff_lan_mode_r3] error received: b'\{"seq":56,"error":400\}'

Unfortunately, I don't know what that means.

As you say, it may be a difference on firmware 3.3 in DIY mode as I have successfully used 3.3 in normal mode too.

I have a switch which I can test this with and will try to see if I can recreate it.

**Comment by Bluhme1** [comment]
I appreciate your effort.
There is a document in Github explaining the DIY mode on this device

https://github.com/itead/Sonoff_Devices_DIY_Tools/blob/master/other/SONOFF%20DIY%20MODE%20Protocol%20Doc.pdf

On page 4 there is a list of error codes telling that error 400 has someting to do with the formatting of Json

**Comment by mattsaxon** [comment]
Thanks, I looked at what I was sending and it looks formatted OK, but having tried a few different formats in the past, perhaps DIY mode is more sensitive. Strange it works for normal mode however. Lets see if I can recreate on my device and try some alternative formats.

Currently sending

>  Sending http message to http://192.168.86.230:8081/zeroconf/switch:

`{'sequence': '1564820177', 'deviceid': '100086f13b', 'selfApikey': '123', 'data': '{"switch": "on"}', 'encrypt': False}`

Things for me to try:

1. Different quotes, single vs double
2. Send as bytes, not as string
3. Check special character 'escaping'
4. See if selfAPIkey and encrypt field as needed

**Comment by mattsaxon** [comment]
Fixed in latest zip file.

Issue was that the data field needed to be an object, whereas it is a string in the example above.
