### ISSUE TITLE
Can't access the "Finding the API key" page

### ISSUE THREAD

**Issue by Stooovie** [mattsaxon/sonoff-lan-mode-homeassistant#21]
Upon clicking the link, I only get an empty page with a banner saying "You do not have permission to update this wiki." Please provide a working link.

**Comment by mattsaxon** [comment]
When and where was the broken link supplied? So I correct that

**Comment by Stooovie** [comment]
Right on the project Github homepage:


https://github.com/mattsaxon/sonoff-lan-mode-homeassistant/blob/master/README.md

Stáhnout Outlook pro iOS<https://aka.ms/o0ukef>

________________________________
Od: mattsaxon <notifications@github.com>
Odesláno: úterý, ledna 21, 2020 2:01 odp.
Komu: mattsaxon/sonoff-lan-mode-homeassistant
Kopie: Stooovie; Author
Předmět: Re: [mattsaxon/sonoff-lan-mode-homeassistant] Can't access the "Finding the API key" page (#21)


When and where was the broken link supplied? So I correct that

**Comment by mattsaxon** [comment]
https://pysonofflanr3.readthedocs.io/encryption.html
