### ISSUE TITLE
Support iFan03

### ISSUE THREAD

**Issue by tsouza85** [mattsaxon/sonoff-lan-mode-homeassistant#23]
I use latest from master branch...

```
- platform: sonoff_lan_mode_r3
  name: Luz Sala
  device_id: 1000954607
  api_key: !secret ventilador_sala_api_key
  outlet: 0
- platform: sonoff_lan_mode_r3
  name: Ventilador Sala
  device_id: 1000954607
  api_key: !secret ventilador_sala_api_key
  outlet: 1
- platform: sonoff_lan_mode_r3
  name: Velocidade 3 Sala
  device_id: 1000954607
  api_key: !secret ventilador_sala_api_key
  outlet: 3
```

Log:
https://termbin.com/qx08

**Comment by mattsaxon** [comment]
@tsouza85 what has changed, was this not working before? Can you describe your issue? A log is helpful, but you need to tell me what you mean by doesn’t work.

**Comment by tsouza85** [comment]
Working with ifan02, but ifan03 don't work...
ifan03 is updated version of ifan02

Status is unavailable

**Comment by mattsaxon** [comment]
Yes, sorry the ifan03 is not currently supported by this library.

**Comment by tsouza85** [comment]
which lib? pysonofflanr3 ?

I am using this component: https://github.com/peterbuga/HASS-sonoff-ewelink works but in cloud

**Comment by mattsaxon** [comment]
That one may well work, but it’s a different library. Correct pysonofflanr3 doesn’t support ifan03.

**Comment by B-Hartley** [comment]
I would be keen to see the ifan03 supported.
If there is anything I can do to help with that, let me know.

I have debug logs from my attempt at using it with this latest library.
eg .

> decrypted data: b'{"light":"off","fan":"off","speed":2,"startup_light":"on","startup_fan":"off","sledOnline":"on"}'
> 2020-05-01 09:55:37 DEBUG (MainThread) [custom_components.sonoff_lan_mode_r3.switch] enter handle_message() b'{"light":"on","fan":"off","speed":1,"startup_light":"on","startup_fan":"off","sledOnline":"on"}'
> 
> 

Thanks

**Comment by mattsaxon** [comment]
I'm stopping maintaining this component, instead I'd recommend using https://github.com/AlexxIT/SonoffLAN . It much more functional and reliable, so any contributions I make in future will be to that repo

**Comment by mattsaxon** [comment]
supported in https://github.com/AlexxIT/SonoffLAN
