### ISSUE TITLE
various switch

### ISSUE THREAD

**Issue by pepebc** [mattsaxon/sonoff-lan-mode-homeassistant#26]
How to add multiple Sonoff switches in Home assistant?

**Comment by mattsaxon** [comment]
Add an entry into configuration.yaml for each switch.

Please post your config that is not working

**Comment by a575606** [comment]
I was going to ask the same question. So the appropriate config is something like this: 

`  - platform: sonoff_lan_mode_r3
    device_id: <dev_id_1>
    name: <name 1>
    api_key: !secret SONOFF_BASIC_1_API
    icon: mdi:lightbulb
  - platform: sonoff_lan_mode_r3
    device_id: <dev_id_2>
    name: <name 2>
    api_key: !secret SONOFF_BASIC_2_API
    icon: mdi:lightbulb
`
... etc? I tried making a list but that seemed to fail

**Comment by mattsaxon** [comment]
Correct. It’s not ideal, but it’s the way it currently works. I have an enhancement open to fix this, but just haven’t got round to it. It performs fine as it is for me and I have over 20 devices
