### ISSUE TITLE
Platform error switch.sonoff_lan_mode_r3

### ISSUE THREAD

**Issue by RavenHuginn** [mattsaxon/sonoff-lan-mode-homeassistant#28]
Hello. I customize Home Assistant 0.107.7
Added settings in configuration.yaml for adding Sonoff mini relays. When checking received the following error:
2020-04-07 19:41:42 ERROR (MainThread) [homeassistant.components.hassio] Platform error switch.sonoff_lan_mode_r3 - Integration 'sonoff_lan_mode_r3' not found.

configuration.yaml
switch:
  - platform: sonoff_lan_mode_r3
    name: Sonoff
    device_id: 1000хххххх
    icon: // [Optional] Custom icon for device
    outlet: 0

![image](https://user-images.githubusercontent.com/20950826/78672802-553ec680-790b-11ea-9e7f-0976d136611f.png)

**Comment by mattsaxon** [comment]
Can you send a directory listing of your custom_components folder please

**Comment by RavenHuginn** [comment]
![image](https://user-images.githubusercontent.com/20950826/78751144-dd6cac80-799b-11ea-8351-dd5c83314d58.png)

![image](https://user-images.githubusercontent.com/20950826/78751170-ebbac880-799b-11ea-9618-f9bf928ed38d.png)

**Comment by mattsaxon** [comment]
And what do you have in the sonoff_lan_mode_r3 directory?

Note, your config should not have the icon line or the outlet line.

**Comment by RavenHuginn** [comment]
A screenshot of the contents of the sonoff_lan_mode_r3 folder in the first message

![image](https://user-images.githubusercontent.com/20950826/78756917-cfbc2480-79a5-11ea-94bc-77538e4d262f.png)

**Comment by mattsaxon** [comment]
Ok, config is correct, assuming Mini is in DIY mode. 

What about the contents of the sonoff_lan_mode_r3 directory?

**Comment by RavenHuginn** [comment]
![image](https://user-images.githubusercontent.com/20950826/78791921-aa95d900-79da-11ea-9116-d3175377ccb3.png)

**Comment by mattsaxon** [comment]
Ah I see it now, all looks good, you’ve done everything right as far as I can see. Issue is with home assistant not spotting the component. There is a previous example of this occurring which seemed related to https being on. Do you have that config?

**Comment by RavenHuginn** [comment]
The error remained. File allocation was like that from the start.
In the config, I only commented out the last two lines in the section.

**Comment by RavenHuginn** [comment]
I am very sorry, I myself was mistaken and misled you. Everything works. Thanks.
