### ISSUE TITLE
Integration fails in HA 0.97.2

### ISSUE THREAD

**Issue by darkopetrovic** [mattsaxon/sonoff-lan-mode-homeassistant#3]
Hello, 

I've an error when trying this component in Home Assistant v0.97.2:

```Integration sonoff_lan_mode_r3 not found when trying to verify its switch platform.```

I tried to put an `__init__.py` but still the same error. 

Thanks.

**Comment by anandsuppiah12** [comment]
Hi. Try disabling Https and login via LAN. Turn on Https back after installation. That worked for me

**Comment by mattsaxon** [comment]
@anandsuppiah12, that's very strange behaviour, I can't see why that would occur. I note that HA 0.98 is now out, can you confirm if this is still an issue?

**Comment by mattsaxon** [comment]
I found this article that seems may have something to do with it https://community.home-assistant.io/t/platform-not-found-for-simple-custom-component-in-0-94-2/121582/26

If I get the error at some point I'll see if this helps diagnose it.

I do have HTTPS on by the way. but have never seen it. However I've had the component installed for sometime.

**Comment by mattsaxon** [comment]
I wonder if it is the download of the requirements from the manifest?

**Comment by darkopetrovic** [comment]
I tried the original `sonoff_lan_mode` components by simply renaming `sonoff_lan_mode_r3` and replacing `manifest.json` and `swtich.py` (restarted HA). Then I recopied back both files from `sonoff_lan_mode_r3` and renamed back the folder to `sonoff_lan_mode_r3` and its working. So I didn't struggling to find why it isn't working the first time. 

Thanks for this component ;)

**Comment by anandsuppiah12** [comment]
Hi Matt, the problem only occured during installation. Unlike darkopetrovic, i had the problem with the older sonoff_lan_mode too. didnt try any other addon so cant comment on that. I dont know the reason, but turning off https did the trick for me. The addon works fine after turning back https on. It could be a 0.97.2 issue. I will uninstall and reinstall in 9.8 to see if I have the same issue later in the day

**Comment by ghost** [comment]
I also encountered this problem, and I tried to turn off HTTPS without any effect. The specific errors are as follows:

![image](https://user-images.githubusercontent.com/50738270/64664813-facbad80-d482-11e9-9bb3-3f40d4e08a40.png)

**Comment by mattsaxon** [comment]
I've added an __init__.py file as suggested here https://community.home-assistant.io/t/91-4-to-92-0-1-custom-components-not-working-anymore/113037

@coolkit-carl, can you check if this works please?

**Comment by mattsaxon** [comment]
Closed as no recurrence, hopefully the thumbs up above suggests that it is fixed!
