### ISSUE TITLE
HACS compatibility

### ISSUE THREAD

**Issue by jomoroga** [mattsaxon/sonoff-lan-mode-homeassistant#30]
Is it possible to make this custom component compatible with HACS?
Thanks in advance!

**Comment by mattsaxon** [comment]
What makes a custom component HACS compatible?

**Comment by jomoroga** [comment]
Hi Matt,
Checking HACS devel documentation and other custom addons, I think it will be necessary only to:
1) Add a folder "custom_components" as parent of the already existing "sonoff_lan_mode_r3" directory, like this:
 - custom_components/sonoff_lan_mode_r3/(*.py)
2) Create a json file in the root, named "hacs.json" containing for example:
{
    "name": "SONOFF LAN MODE R3",
    "domains": ["switch"]
}

Documentation:
https://hacs.xyz/docs/publish/start
https://hacs.xyz/docs/publish/integration

**Comment by mattsaxon** [comment]
Done, tell me if that works for you and if not, please reopen

**Comment by oopiicaa** [comment]
I can confirm it's working. Great and thanks to both of you.

**Comment by mariobarisic** [comment]
@oopiicaa can you assist me. How to add this custom component to HACS? Which URL you are using - I was trying `https://github.com/mattsaxon/sonoff-lan-mode-homeassistant.git` but I'm getting some errors. Thanks

**Comment by oopiicaa** [comment]
https://github.com/mattsaxon/sonoff-lan-mode-homeassistant
(also just _mattsaxon/sonoff-lan-mode-homeassistant_ should do)
Category: Integration

**Comment by mariobarisic** [comment]
OK thank you now is working...
Best regards
