### ISSUE TITLE
Allow client timeout to be configurable

### ISSUE THREAD

**Issue by pveras** [mattsaxon/sonoff-lan-mode-homeassistant#42]
I was getting an `Update message not received in timeout period, retry` message every minute after first using a switch, I imagine because I use Home Assistant on an old RPI with a less than ideal network setup. When these messages started firing up, the switch became very unresponsive.

I changed the local code to create the Switch class with a 20 second timeout and the problem seems to be gone so might be a good idea allow it to be configurable. Also, I'm not sure if the issue I was seeing was actually a bug in the way those requests are retried.

Also, huge thanks for this component, works like a charm!

**Comment by cdantonop** [comment]
I can confirm exactly the same problem. Also, when this happens, Home Assistant can not tell the status of the device. Restarting Home Assistant resolves the problem (for some time).

I use Home Assistant on a decent (for the purpose) Intel-atom laptop. The laptop is connected via Ethernet. The sonoff device is a couple of meters from the wireless access point.

Many thanks for the component from me too!

**Comment by mattsaxon** [comment]
I'm stopping maintaining this component, instead I'd recommend using https://github.com/AlexxIT/SonoffLAN . It much more functional and reliable, so any contributions I make in future will be to that repo
