### ISSUE TITLE
Problems with 0.110b0

### ISSUE THREAD

**Issue by Bluhme1** [mattsaxon/sonoff-lan-mode-homeassistant#44]
Hi
I just installed the new beta 0.110 on my reserve system. The component doesn't work and I get the following error

Logger: homeassistant.components.switch
Source: components/switch/__init__.py:125 
Integration: Kontakt (documentation, issues) 
First occurred: 19.02.56 (1 occurrences) 
Last logged: 19.02.56

SwitchDevice is deprecated, modify HassSonoffSwitchR3 to extend SwitchEntity

Just thought I would tell you as problems probably will appear when everybody upgrades in a week or so.
/Lars

**Comment by maretodoric** [comment]
Just upgraded to 0.110 .0 Stable version and works like a charm

**Comment by oopiicaa** [comment]
True, it does work, but warning is still there:
WARNING (MainThread) [homeassistant.components.switch] SwitchDevice is deprecated, modify HassSonoffSwitchR3 to extend SwitchEntity

**Comment by Bluhme1** [comment]
Works here, too. Stable version but still warning. Might stop working with future releases
