### ISSUE TITLE
Devices become unavailable sometimes even when working in eWeLink

### ISSUE THREAD

**Issue by mattsaxon** [mattsaxon/sonoff-lan-mode-homeassistant#5]
When this happens, in eWeLink, the device is usually marked as Wifi rather than LAN, switching it on/off in eWeLink triggers it back to LAN mode.

**Comment by mattsaxon** [comment]
I'll try to see if periodically running a poll of the devices for, say, signalStrength, can kick it back into LAN mode.

**Comment by FaserF** [comment]
Same issue goes for me. After a reboot of my server it works again most of the time.

**Comment by mattsaxon** [comment]
Would be good to know if you have the same symptom as me. If I go into eWeLink and switch it, it appears in HA immediately. It seems to be that the keep-alive boradcast packets are not being sent, but could also be an issue receipt of these packets.

**Comment by FaserF** [comment]
Yeah, same is for me, directly after opening the ewelink app it is available again

**Comment by mattsaxon** [comment]
What are you running HA on? I’m using Hassio on a RPi 3B+. I’m not sure this issue occurred when I was running HA on Raspbian on a PC. I will get round to retesting this soon, but would be good to know what your running

**Comment by mattsaxon** [comment]
What are you running HA on? I’m using Hassio on a RPi 3+

**Comment by FaserF** [comment]
I am running the latest HA in a phython venv on my Asus Tinkerboard. OS: DietPi latest.

**Comment by mattsaxon** [comment]
I've traced this to an error in ZeroConf. the issue is here https://github.com/jstasiak/python-zeroconf/issues/210.

I've also posted a patch, but we will need to wait until this patch is merged and home assistance migrates to the latest version.

**Comment by mattsaxon** [comment]
I've found some additional information on this.

It does seem that my Rpi is much worse at dropping the packets that other hardware I have. 

I've recorded the hack to reawaken the devices, this appears to have originally worked in older firmware, but has stopped working on more recent ones (not sure exactly when).

Anyway, new patch posted, so I'm closing this issue.

**Comment by mattsaxon** [comment]
Note, the zeroconf error is still there so does need fixing and merging into HA at some point, hopefully the hack will work for these issues too.
