### ISSUE TITLE
Device offline most of the time

### ISSUE THREAD

**Issue by Paul-Vdp** [mattsaxon/sonoff-lan-mode-homeassistant#6]
My device (Sonoff Basic / fw v3.x) ) only comes visible/online a couple of times per day, and only very briefly - a couple of minutes max ...

**Comment by mattsaxon** [comment]
Do you have other devices that are working better?

Is the device visible in eWeLink (not greyed out or shadowed) when it’s not visible in HA?

What does the eWeLink icon next to it look like when you are in your home, is it the WiFi symbol or LAN symbol? A WiFi symbol shows you are having connectivity issues.

Lastly can you post a debug log as described at the bottom of the readme?

**Comment by mattsaxon** [comment]
Closed due to no response.
