### ISSUE TITLE
Switch unavailable after upgrade to 0.112.3

### ISSUE THREAD

**Issue by hukoeth** [mattsaxon/sonoff-lan-mode-homeassistant#63]
Hello,
After upgrading Homeassistant to 0.112.3 the switch shows as unavailable in the UI. Below is the relevant log output and my config. Any idea what might be causing this?

Thanks,
Uli

My config:
switch:
- platform: sonoff_lan_mode_r3
  host: 192.168.2.53
  name: 'Heater Livingroom'
  device_id: someid
  api_key: somekey

Log:
Jul 07 13:52:27 hass[27151]: 2020-07-07 13:52:27 DEBUG (MainThread) [custom_components.sonoff_lan_mode_r3.switch] Initializing SonoffLANModeClient class in SonoffDevice
Jul 07 13:52:27 hass[27151]: 2020-07-07 13:52:27 DEBUG (MainThread) [custom_components.sonoff_lan_mode_r3.switch] HassSonoffSwitch __init__ finished creating SonoffSwitch
Jul 07 13:52:27 hass[27151]: 2020-07-07 13:52:27 DEBUG (MainThread) [custom_components.sonoff_lan_mode_r3.switch] enter send_availability_loop()
Jul 07 13:52:27 hass[27151]: 2020-07-07 13:52:27 DEBUG (MainThread) [custom_components.sonoff_lan_mode_r3.switch] waiting for connection
Jul 07 13:52:27 hass[27151]: 2020-07-07 13:52:27 DEBUG (MainThread) [custom_components.sonoff_lan_mode_r3.switch] send_updated_params_loop is active on the event loop
Jul 07 13:52:27 hass[27151]: 2020-07-07 13:52:27 DEBUG (MainThread) [custom_components.sonoff_lan_mode_r3.switch] Starting loop waiting for device params to change
Jul 07 13:52:27 hass[27151]: 2020-07-07 13:52:27 DEBUG (MainThread) [custom_components.sonoff_lan_mode_r3.switch] send_updated_params_loop now awaiting event
Jul 07 13:52:27 hass[27151]: 2020-07-07 13:52:27 WARNING (zeroconf-ServiceBrowser__ewelink._tcp.local._2795824224) [zeroconf] Error sending through socket 10
Jul 07 13:52:27 hass[27151]: Traceback (most recent call last):
Jul 07 13:52:27 hass[27151]:   File "/opt/homeassistant/lib/python3.7/site-packages/zeroconf/__init__.py", line 2792, in send
Jul 07 13:52:27 hass[27151]:     bytes_sent = s.sendto(packet, 0, (real_addr, port))
Jul 07 13:52:27 hass[27151]: OSError: [Errno 126] Required key not available
Jul 07 13:52:27 hass[27151]: 2020-07-07 13:52:27 DEBUG (MainThread) [custom_components.sonoff_lan_mode_r3.switch] HassSonoffSwitch async_update called
Jul 07 13:52:27 hass[27151]: 2020-07-07 13:52:27 DEBUG (MainThread) [custom_components.sonoff_lan_mode_r3.switch] Sonoff device basic info still none, waiting for init message
Jul 07 13:52:27 hass[27151]: 2020-07-07 13:52:27 DEBUG (MainThread) [custom_components.sonoff_lan_mode_r3.switch] HassSonoffSwitch returning _name: Heater Livingroom
Jul 07 13:52:27 hass[27151]: 2020-07-07 13:52:27 DEBUG (MainThread) [custom_components.sonoff_lan_mode_r3.switch] HassSonoffSwitch returning _available: False
Jul 07 13:52:27 hass[27151]: 2020-07-07 13:52:27 DEBUG (MainThread) [custom_components.sonoff_lan_mode_r3.switch] HassSonoffSwitch returning _name: Heater Livingroom
Jul 07 13:52:28 hass[27151]: Exception in thread zeroconf-ServiceBrowser__ewelink._tcp.local._2795824224:
Jul 07 13:52:28 hass[27151]: Traceback (most recent call last):
Jul 07 13:52:28 hass[27151]:   File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
Jul 07 13:52:28 hass[27151]:     self.run()
Jul 07 13:52:28 hass[27151]:   File "/opt/homeassistant/lib/python3.7/site-packages/zeroconf/__init__.py", line 1679, in run
Jul 07 13:52:28 hass[27151]:     state_change=service_type_state_change[1],
Jul 07 13:52:28 hass[27151]:   File "/opt/homeassistant/lib/python3.7/site-packages/zeroconf/__init__.py", line 1433, in fire
Jul 07 13:52:28 hass[27151]:     h(**kwargs)
Jul 07 13:52:28 hass[27151]:   File "/opt/homeassistant/lib/python3.7/site-packages/zeroconf/__init__.py", line 1531, in on_change
Jul 07 13:52:28 hass[27151]:     listener.add_service(*args)
Jul 07 13:52:28 hass[27151]:   File "/opt/homeassistant/lib/python3.7/site-packages/pysonofflanr3/client.py", line 118, in add_service
Jul 07 13:52:28 hass[27151]:     found_ip = utils.parseAddress(info.address)
Jul 07 13:52:28 hass[27151]: AttributeError: 'ServiceInfo' object has no attribute 'address'

**Comment by hukoeth** [comment]
Sorry didn't see the "no longer maintained" notice.

**Comment by mattsaxon** [comment]
You are welcome to leave this open as someone might fork this

**Comment by mattsaxon** [comment]
Closing as https://github.com/AlexxIT/SonoffLAN is much better integration so this will never get forked.
